### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by SinhtUp** [tomi77/atom-npm#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: HAMIT-LAPI
**Thrown From**: [atom-npm](https://github.com/tomi77/atom-npm) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'filename' of undefined

```
At C:\Users\Ufuk Hamit Alkin\.atom\packages\atom-npm\node_modules\npm\lib\utils\lifecycle.js:76

TypeError: Cannot read property 'filename' of undefined
    at /packages/atom-npm/node_modules/npm/lib/utils/lifecycle.js:76:37
    at /packages/atom-npm/node_modules/npm/lib/utils/lifecycle.js:163:12
    at /packages/atom-npm/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
    at FSReqCallback.oncomplete (fs.js:159:5)
```

### Commands

```
     -0:20.8.0 atom-npm:install-dependencies (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-html-preview 0.2.7 
atom-npm 0.3.1 
autocomplete-unity 0.1.3 
emmet 2.4.3 
jQuery 1.3.0 
language-unityscript 0.37.0 
minimap 4.40.0 
react 0.18.0 
unity-shader-files 0.3.1 
```

**Comment by Sam-Buckley** [comment]
I've got this issue aswell
i hope someone sees this soon
